### ISSUE TITLE
Axios error: options must be an object

### ISSUE THREAD

**Issue by anastasia-naydenko** [storyblok/storyblok-vue-2#117]
Hi there!

Node version 16
Vue.js version 2.6.14
"@storyblok/vue-2": "^2.0.1"
"axios": "^1.1.3"

The code:
const { data } = await storyblokApi.get('cdn/stories/home', { cv: {}, version: 'published' });

The error:
AxiosError {message: 'options must be an object', name: 'AxiosError', code: 'ERR_BAD_OPTION_VALUE', stack: 'AxiosError: options must be an object\n    at Objec…@storyblok/vue-2/dist/storyblok-vue-2.mjs:547:28)'}
code: "ERR_BAD_OPTION_VALUE"
message: "options must be an object"
name: "AxiosError"
stack: "AxiosError: options must be an object\n    at Object.assertOptions (webpack-internal:///./node_modules/axios/lib/helpers/validator.js:70:11)...

**Comment by anastasia-naydenko** [comment]
Please fix, or delete paramsSerializer
![image](https://user-images.githubusercontent.com/109067724/197165295-b51c5f85-7e1a-47a8-bdac-219cace8c9a5.png)
